global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules/kafka-alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: kafka_jmx
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka-jmx-prom-exporter:9404

  - job_name: node_exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-exporter:9100
